name: Build NEET 3D APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# ఇక్కడ పర్మిషన్స్ యాడ్ చేశాం, దీనివల్ల బిల్డ్ ఫెయిల్ అవ్వదు
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache git libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev ioquake3-server libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstreamer-plugins-base1.0-dev libasound2-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev liblzma-dev org-mode-doc openjdk-17-jdk unzip zip
        sudo apt-get install -y python3-pip python3-setuptools python3-dev
        pip3 install --user --upgrade buildozer cython virtualenv kivy

    - name: Build Android APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Master-APK-File
        path: bin/*.apk
